Ecommerce/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Ecommerce/cart/urls.py
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
        path('add_cart/<int:p>/',views.add_cart,name="add_cart"),
        path('cart_view/',views.cart_view,name="cart_view"),
        path('cart_remove/<int:p>/',views.cart_remove,name="cart_remove"),
        path('full_remove/<int:p>/',views.full_remove,name="full_remove"),
        path('orderform/',views.order,name="orderform"),
        path('orderview/',views.orderview,name="orderview"),

]

Ecommerce/search/urls.py
from django.urls import path
from search import views
app_name="search"
urlpatterns = [

    path('searchresult/',views.searchresult,name="searchresult"),

]

Ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [

    path('',views.allProdCat,name="allprodcat"),
    path('allproducts/<slug:cslug>',views.allproducts,name="allproducts"),
    path('prodetail/<slug:pslug>',views.prodetail,name="prodetail"),
    path('register/',views.register,name="register"),
    path('login/',views.user_login,name="user_login"),
    path('logout/',views.user_logout,name="user_logout"),

]

Ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    date_added=models.DateField(auto_now_add=True)
    quantity=models.IntegerField(default=1)
    active=models.BooleanField(default=True)

    def __str__(self):
        return self.products.name

class Account(models.Model):
    acctnumber=models.CharField(max_length=200)
    accttype=models.CharField(max_length=200)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnumber
class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    address=models.TextField()
    phone=models.CharField(max_length=100)
    order_status=models.CharField(max_length=30,default="pending")
    delivery_status = models.CharField(max_length=30,default="pending")
    noofitems=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str_(self):
        self.user.username
    def subtotal1(self):
        return self.noofitems*self.products.price

Ecommerce/search/models.py
from django.db import models

# Create your models here.

Ecommerce/shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='shop/category',null=True,blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="img/products",null=True,blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

Ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from shop.models import Product
from cart.models import Cart,Account,Order

# Create your views here.
def cart_view(request):
    total=0

    try:
        user=request.user
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.products.price

    except Cart.DoesNotExist:
        pass
    return render(request,'cart.html',{'cart':cart,'total':total})




@login_required
def add_cart(request,p):
    product=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(products=product,user=user)
        if cart.quantity < cart.products.stock:
            cart.quantity+=1
        cart.save()
    except Cart.DoesNotExist:
        cart=Cart.objects.create(products=product,user=user,quantity=1)
        cart.save()
    return redirect('cart:cart_view')

@login_required
def cart_remove(request,p):
    user=request.user
    product=Product.objects.get(id=p)
    try:
        cart=Cart.objects.get(products=product,user=user)
        if cart.quantity > 1:
            cart.quantity -= 1
            cart.save()
        else:
            cart.delete()

    except:
        pass
    return redirect('cart:cart_view')

@login_required

def full_remove(request,p):
    user=request.user
    product=Product.objects.get(id=p)
    try:
        cart=Cart.objects.get(user=user,products=product)
        cart.delete()
    except:
        pass
    return redirect('cart:cart_view')
@login_required
def order(request):
    total=0
    items=0
    msg=0
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        num=request.POST['num']
        user=request.user
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.products.price
            items+=i.quantity

        ac=Account.objects.get(acctnumber=num)
        if float(ac.amount) >= total:
            ac.amount=ac.amount-total
            ac.save()
            for i in cart:
                o=Order.objects.create(user=user,products=i.products,address=a,phone=p,order_status="paid",noofitems=i.quantity)
                o.save()
            cart.delete()
            msg="Order Placed Successfully"
            return render(request,'orderdetail.html',{'msg':msg,'total':total,'items':items})
        else:
            msg="You can't place order due to insufficient balance."
            return render(request,'orderdetail.html',{'msg':msg})

    return render(request,'orderform.html')

@login_required
def orderview(request):
    user=request.user
    o=Order.objects.filter(user=user,order_status="paid")
    return render(request,'orderview.html',{'o':o})

Ecommerce/search/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db.models import Q
from shop.models import Product
# Create your views here.
def searchresult(request):
    products=None
    query=None
    if request.method=="POST":
        query=request.POST.get('q')
        if query:
            products=Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request,'search.html',{'query':query,'products':products})

Ecommerce/shop/views.py
from django.shortcuts import render
from shop.models import Category,Product
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
# Create your views here.

def allProdCat(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})

def allproducts(request,cslug):
    c=Category.objects.get(slug=cslug)
    p=Product.objects.filter(category__slug=cslug)
    return render(request,'products.html',{'p':p,'c':c})

def prodetail(request,pslug):
    p=Product.objects.get(slug=pslug)
    return render(request,'detail.html',{'p':p})

def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        f = request.POST['f']
        l = request.POST['l']
        e = request.POST['e']
        p=request.POST['p']
        cp = request.POST['cp']
        if p==cp:
            user=User.objects.create_user(username=u,first_name=f,last_name=l,email=e,password=p)
            user.save()
            return allProdCat(request)
    return render(request, 'register.html')


def user_login(request):
    if (request.method == "POST"):
        u = request.POST['u']
        p = request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return allProdCat(request)
        else:
            messages.error(request,"Invalid Credential")
    return render(request,"login.html")

def user_logout(request):
    logout(request)
    return allProdCat(request)

Ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

</head>

<body>
<div class="container-fluid">
    <header>
        <center><img src="{% static 'img/logo5.png' %}" height="70px" width="90px"></center>
            <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#800020;">

                <div class="container-fluid">
                    <a class="navbar-brand" href="#">Shopping</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'shop:allprodcat' %}">Home</a>
                        </li>



                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Shop
                            </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'shop:allprodcat' %}">All Categories</a></li>
                        {% for i in links %}
                            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.slug %}">{{i.name}}</a></li>
                        {% endfor %}
                    </ul>
                        </li>
    {% if user.is_authenticated %}

                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'shop:user_logout' %}">Logout</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'cart:cart_view' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i>{{item_count}}</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
                        </li>
        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'shop:register' %}">Register</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'shop:user_login' %}">Login</a>
                        </li>



    {% endif %}

                    </ul>

            <form class="d-flex" action="{% url 'search:searchresult' %}" method="POST">
                {% csrf_token %}
                <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                 <button class="btn btn-outline-success" type="submit"><i class="fa-sharp fa-solid fa-magnifying-glass"></i></button>
            </form>

                </div>

                </div>

            </nav>
    </header>
            {% block content %}
            {% endblock %}
    <footer class="footer">
        <div>
            <p> <i class="fa-solid fa-copyright"></i>Myshop pvt ltd.All rights reserved.</p>
        </div>
    </footer>

</div>

</body>
</html>

Ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    {% if not cart  %}
    <div>
        <h1 class="text-center">Cart is Empty</h1>
    </div>
    <div>
        <strong><a href="{% url 'shop:allprodcat' %}">Continue Shopping</a></strong>
    </div>
    {% else %}
    <div class="row mx-auto">
        <h1 class="text-center" style="width=100%;margin:20px;">Shopping Cart</h1>
        <div class="col-sm-6">
            <table class="table table-bordered">
                <tr>
                    <th colspan="5" class="text-center">
                        YOUR ITEMS
                    </th>
                </tr>
                {% for i in cart %}
                <tr>
                    <td><img src="{{i.products.image.url}}" style="height:150px;width:150px;"></td>
                    <td>{{i.products.name}}</td>
                    <td>Pid:{{i.products.id}}<br>
                        Unit Price:{{i.products.price}}<br><br>
                        Quantity:{{i.quantity}}*{{i.products.price}}<br>
                    </td>
                    <td>Subtotal:{{i.subtotal}}</td>
                    {% if i.quantity < i.products.stock %}
                    <td>
                        <a href="{% url 'cart:cart_remove' i.products.id %}"><i class="fa fa-minus-circle custom_icon" aria-hidden="true"></i> </a>
                        <a href="{% url 'cart:add_cart' i.products.id %}"><i class="fa fa-plus-circle custom_icon" aria-hidden="true"></i> </a>
                        <a href="{% url 'cart:full_remove' i.products.id %}"><i class="fa fa-trash custom_icon" aria-hidden="true"></i></a>
                    </td>
                     {% else %}
                        <td>
                        <a href="{% url 'cart:cart_remove' i.products.id %}"><i class="fa fa-minus-circle custom_icon" aria-hidden="true"></i> </a>
                        <a href="{% url 'cart:full_remove' i.products.id %}"><i class="fa fa-trash custom_icon" aria-hidden="true"></i></a>
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}

            </table>
        </div>



        <div class="col-sm-6">
            <table class="table table-bordered">
                <tr>
                <th colspan="5" class="text-center">
                    CHECK OUT
                </th>
                </tr>
                <tr>
                    <th>Total Price:{{total}}</th>
                </tr>
            </table>
            <a class="btn btn-primary" href="{% url 'shop:allprodcat' %}">Continue Shopping</a>&nbsp
            <a class="btn btn-primary" href="{% url 'cart:orderform'  %}">Place order</a>
        </div>
        {% endif %}
    </div>
</div>



{% endblock %}

Ecommerce/templates/cart1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-bottom=100px">
    {% if not cart %}
    <div>
        <h1 class="text-center">cart is empty</h1>
    </div>
    <div>
        <strong><a href="{% url 'shop:allprodcat' %}"> continue shopping</a></strong>
    </div>
    {% else %}
    <div class="row mx_auto">
        <h1 style="-width:100%;">shopping cart</h1>

        <div class="col-sm-6">
            <table class="table table-bordered">
                <tr>
                <th colspan="6" class="text-center">
                    YOUR ITEMS
                </th></tr>
                    {% for i in cart %}
               <tr>
                   <td><img src="{{i.products.image.url}}" style="height:150px;width:150px"></td>
                   <td>{{i.products.name}}</td>
                   <td>p id:{{i.products.id}}<br>
                       unit price:{{i.products.price}}<br>
                       quantity:{{i.quantity}}*{{i.products.price}}<br>

                   </td>
                   <td>subtotal:{{i.subtotal}}</td>
                   {% if i.quantity < i.products.stock %}
                   <td><a href="{% url 'cart:addcart' i.products.id %}"><i class="fa-solid fa-circle-plus custom_icon"></i></a>
                       <a href="{% url 'cart:cart_remove' i.products.id %}"><i class="fa-solid fa-circle-minus custom_icon"></i></a>
                       <a href="{% url 'cart:full_remove' i.products.id %}"><i class="fa-sharp fa-solid fa-trash custom_icon"></i></a>
                   </td>
                   {% else %}
                    <td>
                       <a href="{% url 'cart:cart_remove' i.products.id %}"><i class="fa-solid fa-circle-minus custom_icon"></i></a>
                       <a href="{% url 'cart:full_remove' i.products.id %}"><i class="fa-sharp fa-solid fa-trash custom_icon"></i></a>
                   </td>
                   {% endif %}
               </tr>
                {% endfor %}
            </table>
        </div>
        {% endif %}
        <div class="col-sm-6">
            <table class="table table-bordered">
                <tr>
                    <th colspan="5" class="text-center">checkout</th>
                </tr>
                <tr>
                    <th colspan="5">Total price:   {{total}}</th>
                </tr>
            </table>
            <button class="btn btn-primary" href="{% url 'shop:allprodcat' %}">continue shopping</button>
            <button class="btn btn-primary" href=" " >place order</button>
        </div>
    </div>
</div>
{% endblock %}

Ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'img/banner1.jpg' %}" height="250px" width="100%">

</div>
<div style="margin:50px">
    <h5>Our Collections</h5>
    <p class="text-justify ">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
</div>
<div class="container" style="margin-bottom:100px" >
    <div class="row mx-auto" >
        {% for i in c %}
        <div class="col-4">
            <div class="card" style="width: 18rem;">
            <img src="{{i.image.url}}" style="height:200px;width:100%" class="card-img-top" alt="{{i.name}}">
                <div class="card-body" style="height:160px;width:100%">
                    <h5 class="card-title">{{i.name}}</h5>
                    <a href="{% url 'shop:allproducts' i.slug %}" class="btn btn-primary link" style="position:absolute;top:280px;">PRODUCTS</a>
                </div>
            </div>
        </div>
    {% endfor %}

    </div>
</div>
{% endblock %}

Ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin:20px" >
    <div class="row mx-auto">
        <div class="col-sm-6">
            <img src="{{p.image.url}}" height="350px" width="350px%"alt="{{p.image.url}}">
        </div>
        <div class="col-sm-6">
            <h1>{{p.name}}</h1>
            <p>{{p.price}}</p>
            <h3>Product description</h3>
            <p>{{p.description}}</p>
            {% if p.stock <= 0 %}
            <h2>OUT OF STOCK</h2>
            {% else %}
            <a class="btn btn-primary" href="{% url 'cart:add_cart' p.id %}">ADD TO CART</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

Ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center><h3 class="text-dark">Login</h3></center>
<div class="container">

    <form method="POST">
      {% csrf_token %}
      <div class="mb-3">
      <label  class="form-label">Username</label>
      <input type="text" class="form-control" name="u" placeholder="Enter username">
      </div>

      <div class="mb-3">
      <label  class="form-label">Password</label>
      <input type="password" class="form-control" name="p" placeholder="Enter password">
      </div>

      <div class="mb-3">
      <input type="submit" class="btn btn-primary">
      </div></form>
      {% if messages %}
      {% for i in messages %}
      <ul class="messages">
          <li>{{i}}</li>
      </ul>
      </div>
      {% endfor %}
      {% endif %}



{% endblock  %}

Ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<div class="container" style="margin-bottom:100px;">
  <h1 class="text-dark">Your Order Placed Successfully</h1>
  <p>Thank you...</p>
  <a class="btn btn-danger" href="{% url 'shop:allprodcat' %}">Continue Shopping</a>
 </div>
</center>




{% endblock  %}

Ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">

    <form method="POST">
      {% csrf_token %}
      <div class="mb-3">
      <label  class="form-label">Address</label>
      <textarea class="form-control" name="a" placeholder="Enter address" rows="3"></textarea>
      </div>

      <div class="mb-3">
      <label  class="form-label">Phone Number</label>
      <input type="text" class="form-control" name="p" placeholder="Enter phone number">
      </div>

      <div class="mb-3">
      <label  class="form-label">Account Number</label>
      <input type="text" class="form-control" name="num" placeholder="Enter account number">
      </div>

      <div class="mb-3">
      <input type="submit" class="btn btn-primary">
      </div>
    </form>
</div>


{% endblock %}

Ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-bottom:10px;">
    <div class="row mx-auto" style="margin:10px;">

        <b><h5>Customer Name: {{user}}</h5></b>
        {% for i in o %}

        <div class="col-sm-4" style="border:1px solid purple;">
           <center> <img src="{{i.products.image.url}}" style="height:150px;width:150px;margin:20px;"></center>
        </div>
        <div class="col-sm-8" style="border:1px solid purple;">
            <h6><strong>Product:</strong>{{i.products.name}}</h6>
            <h6><strong>Delivery Address:</strong>{{i.address}}</h6>
            <h6><strong>PhoneNumber:</strong>{{i.phone}}</h6>
            <h6><strong>Price:{{i.products.price}}</strong></h6>
            <h6><strong>Quantity:{{i.noofitems}}</strong></h6>
            <h6><strong>Subtotal:{{i.subtotal1}}</strong></h6>
            <h6 class="text-warning">Ordered On:{{i.date_added}}</h6>
            <h6 class="text-warning">Delivery Status:{{i.delivery_status}}</h6>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock  %}

Ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div>
    <img src="{{c.image.url}}" height="250px" width="100%">
</div>
<div style="margin:50px">
    <h1 class="text-center">{{c.name}}</h1>
    <p class="text-justify "></p>
</div>
<div class="container" style="margin-bottom:100px" >
    <div class="row mx-auto" >
    {% for i in p %}
        <div class="col-4">
            <div class="card" style="width: 18rem;">
            <img src="{{i.image.url}}" style="height:200px;width:100%" class="card-img-top" alt="{{i.name}}">
                <div class="card-body" style="height:200px;width:100%">
                    <h5 class="card-title">{{i.name}}</h5>
                    <a href="{% url 'shop:prodetail' i.slug %}" class="btn btn-primary link"style="position:absolute;top:300px;">DETAILS</a>
                </div>
            </div>
        </div>

    {% endfor %}
    </div>
</div>
{% endblock %}

Ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px">
<center><h3 class="text-dark">Registration</h3></center>


    <form method="POST">
      {% csrf_token %}
      <div class="mb-3">
      <label  class="form-label">Username</label>
      <input type="text" class="form-control" name="u" placeholder="Enter username">
      </div>

      <div class="mb-3">
      <label  class="form-label">First_name</label>
      <input type="text" class="form-control" name="f" placeholder="Enter first name">
      </div>

      <div class="mb-3">
      <label  class="form-label">Last_name</label>
      <input type="text" class="form-control" name="l" placeholder="Enter last name">
      </div>

      <div class="mb-3">
      <label  class="form-label">email</label>
      <input type="email" class="form-control" name="e" placeholder="Enter email">
      </div>

      <div class="mb-3">
      <label  class="form-label">Password</label>
      <input type="password" class="form-control" name="p" placeholder="Enter password">
      </div>

      <div class="mb-3">
      <label  class="form-label">Confirm Password</label>
      <input type="password" class="form-control" name="cp" placeholder="R-enter password">
      </div>

      <div class="mb-3">
      <input type="submit" class="btn btn-primary">
      </div>
    </form>
</div>

{% endblock  %}

Ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div style="margin-top:20px">
        <h3><b>You Have Searched for {{query}}</b></h3>
    </div>
</center>

<div class="container" style="margin-bottom:100px;margin-top:20px" >
    <div class="row mx-auto" >
    {% for i in products %}
        <div class="col-4">
            <div class="card" style="width: 18rem;">
            <img src="{{i.image.url}}" style="height:200px;width:100%" class="card-img-top" alt="{{i.name}}">
                <div class="card-body" style="height:200px;width:100%">
                    <h5 class="card-title">{{i.name}}</h5>
                    <a href="{% url 'shop:prodetail' i.slug %}" class="btn btn-primary link"style="position:absolute;top:300px;">DETAILS</a>
                </div>
            </div>
        </div>
    {% empty %}
     <div>
         <p>0 RESULTS FOUND</p>
     </div>
    {% endfor %}
    </div>
</div>

{% endblock %}